### ISSUE TITLE
Migrate from `Azure-pipeline` to `Github Action`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#2664]
# Part 1: Migration

- [x] #2524
- [x] #2648
- [x] #2654
- [x] #2656
- [x] #2661 
- [x] #2662
- [x] #2663

# Part 2: Decommission

- [x] #2659 
- [x] Decommission Linux Steps in `Azure-pipeline` in #2739
- [x] Decommission Windows Steps in `Azure-pipeline` in #2739
- [x] Decommission MacOS Steps in `Azure-pipeline` in #2739
- [ ] Decommission Linux packaging steps in `Azure-pipeline`
- [ ] Decommission Windows packaging steps in `Azure-pipeline`
- [ ] Decommission MacOS packaging steps in `Azure-pipeline`

**Comment by FirelightFlagboy** [comment]
We're using github action now
