### ISSUE TITLE
Oxidize `UserStorage`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3168]
`UserStorage` depends on `ManifestStorage` so to simplify the migration.
I suggest we first migrate `ManifestStorage` (tracked in #3169) then migrate `UserStorage`

# TODOs

- [ ] Remove the dependency on the python class `ManifestStorage` (the class in implemented in Rust but not binded see #3169)
- [ ] Replace the python class `UserStorage` with the Rust one using `pyo3`
- [ ] Correct the fixture `initialize_local_user_manifest` at `tests/fixtures.py`
- [ ] Correct the fixture `initialize_local_user_manifest` at `tests/common/binder.py`
- [ ] Correct the fixture `alice_user_storage` at `tests/core/fs/storage/test_user_storage.py`
- [ ] Correct the test `test_initialization` at `tests/core/fs/storage/test_user_storage.py` 
- [ ] Correct the test `test_storage_file_tree` at `tests/core/fs/storage/test_user_storage.py`
