### ISSUE TITLE
Oxidize `ManifestStorage`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3169]
# TODOs

- [ ] include change from #3224
- [ ] Replace the python class by the Rust one using `pyo3`
- [ ] Correct the test `test_workspace_manifest_access_while_speculative` at `tests/core/fs/test_bootstrap.py`
