### ISSUE TITLE
Remove `LocalDatabase` after oxidation

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3170]
Remove the python class `LocalDatabase` after oxidation of the last classes that where using it. 

# Depend on 

- #3168 
- #3169 

# TODOs

- [ ] Remove the class `LocalDatabase`
- [ ] Rewrite the suite tests `test_disk_full` at `tests/core/fs/test_disk_full.py`
- [ ] Rewrite the test `test_workspace_manifest_access_while_speculative` at `tests/core/fs/test_bootstrap.py`
- [ ] Rewrite the fixture `persistent_mockup` at `tests/conftest.py`

> Reminder the goal of the rewrite is to not have the class `LocalDatabase` defined in the python code base.
