### ISSUE TITLE
Oxidize exception `ProtocolError`

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3172]
## Todos 

- [x] #3653
- [ ] The `ProtocolError` in Rust can be created from:
    - [ ] `::rmp_serde::encode::Error` ~(currently a string)~
    - [ ] `::rmp_serde::decode::Error` ~(currently a string)~
    - [ ] `std::num::TryFromIntError`
- [ ] The `ProtocolError` in Python can be created from `str`

https://pyo3.rs/latest/function/error_handling.html#foreign-rust-error-types

**Comment by Volham22** [comment]
Isn't `ProtocolError` already created on master when a `rmp_serde::encode` and `rmp_serde::encode` error occurs [here](https://github.com/Scille/parsec-cloud/blob/0dcdb84f33a035c6061baf4d897bb9741c7c8f14/src/protocol/mod.rs#L146) and [here](https://github.com/Scille/parsec-cloud/blob/0dcdb84f33a035c6061baf4d897bb9741c7c8f14/src/protocol/mod.rs#L155)?

We can also do the following on master since #3653 :

```
Python 3.9.13 (main, Nov  7 2022, 09:39:17)
[GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from parsec._parsec import ProtocolError
>>> err = ProtocolError("some error")
>>> err
ProtocolError('some error')
```
