### ISSUE TITLE
Oxidize Backend Connection

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#3868]
Oxidize the python code located here [/parsec/core/backend_connection/](https://github.com/Scille/parsec-cloud/tree/master/parsec/core/backend_connection)

# TODO 

- [ ] `client_connection` provide a way to send anonymous  
- [ ] `client_connection` provide a way to send invite cmds
- [ ] `client_connection` provide a way to config the http client
  - with proxy url
  - with certificate autority
- [ ] Use `client_connection` crate in place of `transport.py`
- [ ] Translate authenticated cmds
- [ ] Translate invited cmds
- [ ] Translate anonymous cmds
- [ ] Provide binding for `BackendAuthenticatedCmds`
- [ ] Provide binding for `BackendInvitedCmds`
- [ ] Provide anonymous cmds in a meta class `BackendAnonymousCmds`
  - `pki_enrollment_submit`
  - `pki_enrollment_info`
  - `organization_bootstrap`

# POC Send authenticated cmds

1. [ ] Provide a pyo3 binding for `client_connection::AuthenticatedCmds` must be async take example of the binding of `TimeProvider`
2. [ ] Write test to use the binded `AuthenticatedCmds` with the RPC backend to send / receive ping cmd
