### ISSUE TITLE
Log support in Rust code

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#3930]
## Log support requirement

- [x] We also want to have the logs enable during the rust tests #4219 
- [x] ~Sentry support~ (see #6458)
  ~If we use the `tracing` crate, we could use [sentry-tracing](https://crates.io/crates/sentry-tracing).~
  ~If we directly plug to python, python will handle sending the log to sentry.~
- [x] ~Python integration~ (see #6459)

  > We want python & rust to share the same logging system.
  > So it's either `python -> rust` or `rust -> python` (`->` = `that use the logging system of`)

  Some interesting links:

  - https://github.com/PyO3/pyo3/blob/main/guide/src/ecosystem/logging.md
  - https://github.com/danielschemmel/tracing-for-pyo3-logging
  - https://docs.rs/pyo3-log/0.8.1/pyo3_log/
  - PyO3/pyo3#1208

If we want to use both `tracing` crate and `log` crate, we could use [tracing-log](https://crates.io/crates/tracing-log) (included by default in `tracing-subscriber`)

## Converting `print` into `log` entry

- [x] Replace `eprintln` in `core_fs::ManifestStorage::close_connection` to `log::warn`
- [x] Replace `println` in `texts_fixtures::testbed::ensure_testbed_server_is_started` to `log::info`
- [x] Add `log::info` at the end of `local_db::BackgroundSqliteExecutor::serve`
- [x] Replace `eprintln` in `local_db::SqliteExecutor::exec` to `log::warn`
- [x] Replace `eprintln` in `local_db::LocalDatabase::exec_job` to `log::warn`

**Comment by touilleMan** [comment]
Regarding pyo3-log, deadlock might occurs when a log is done [while the GIL is already held](https://docs.rs/pyo3-log/0.8.1/pyo3_log/#interaction-with-python-gil)

This is not as bad as it seems given it only occurs when the log is done from a spawned thread while the initial thread holding the GIL waits on it.
In our bindings we should never need to do that (given we send the work in the tokio thread pool before doing any work).

Another solution to avoid this is to dedicate a background thread to the log (the log functions would then only push a message for this thread, which would itself do the GIL lock). The additional benefit of this approach is it avoids GIL congestion (and hence performance drop) in the Rust threads.
