### ISSUE TITLE
Rust-analyzer no annotation when using the testbed crate

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#4308]
When I was working with `client_connection` crate on the tests that use `TestbedScope`,

`rust-analyzer` could not provide annotation for the param provided in the closure (witch should be `Arc<TestbedEnv>`).

Even when importing `TestbedEnv` from the crate `testbed` it still no provide annotation and could not find the definition of `TestbedEnv`.

## TODOs

- [x] #4386
- [ ] Break cyclic dependencies in `libparsec_testbed`
- [x] #4397
- [ ] Break cyclic dependencies in `libparsec_platform_local_db`
- [ ] Break cyclic dependencies in `libparsec_platform_device_loader`
- [ ] Break cyclic dependencies in `libparsec_serialization_format`

**Comment by touilleMan** [comment]
Rust analyzer now works fine with `TestbedEnv` \o/
