### ISSUE TITLE
Final oxidation meta-issue 🦫

### ISSUE THREAD

**Issue by touilleMan** [Scille/parsec-cloud#4567]
The target branch is [castor](https://github.com/Scille/parsec-cloud/tree/castor) 🦫🦫🦫

## When should we merge into `master` ?

Given this branch introduce a huge number of changes, we might want to just merge it into master asap (and accepting breaking master in the process). This would avoid useless conflicts.

And if we need to release a new version in the meantime, we can start from `v2.15.1`.

What do you think ?

## Legend

🦀: Rust
🐍: Python
🔨: Test
📜: API
✋: I work alone on this
🙏: Help needed
🍭: Bonus (not blocking for merge)
🤔: Some thinking needed

## Items

- [x] #4574
- [x] #4573
- [x] #4572
- [ ] #4562
- [x] #4540
- [x] #4541
- [x] #4542
- [ ] #4561
- [x] #4568
- [ ] #4560
- [x] #4553
- [x] #4559
- [x] #4558
- [x] #4564
- [ ] #4565
- [ ] #4563
- [ ] #4566
- [x] #4557
- [x] #4546
- [x] #4554
- [x] #4555
- [ ] #4556
- [ ] #4552
- [ ] #4551
- [ ] #4550
- [x] #4549
- [ ] #4548
- [x] #4547
- [x] #4543
- [ ] #4544
- [x] #4545
- [x] #4577
- [x] #4578
- [x] #4579
- [ ] #4580
- [x] #4581
- [x] #4582
- [x] Expose User Ops to high level API 🦀✋
- [x] Expose Certificates Ops to high level API 🦀✋
- [x] Implement User Ops sync 🦀✋
- [x] Implement User Ops workspace share 🦀✋
- [ ] Implement User Ops workspace reencryption 🦀✋
- [x] Implement User Ops process last message 🦀✋
- [x] Implement Certificates Ops user/device/realm_role lookup methods 🦀✋
- [x] Implement Certificates Ops consistency rules 🦀✋

**Comment by FirelightFlagboy** [comment]
I've rewrited the issue body to use a task list, that will automatically update the state of that tracking issue when the underlying issue are closed

**Comment by touilleMan** [comment]
replaced by the https://github.com/Scille/parsec-cloud/milestone/13
