### ISSUE TITLE
Configure GA for automatic Apple electron app sign & notorization

### ISSUE THREAD

**Issue by FirelightFlagboy** [Scille/parsec-cloud#7724]
Depends on #7723

## TODOs

- [x] Generate a dedicated apple sign certificate for the repository

   <https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/#generating-the-certificate>

   1. Generate a CSR with:

      ```yaml
      CN: Parsec cloud GA
      User email: services@scille.fr
      CA email: services@scille.fr
      ```
   2. Generate Certificate using the CSR on the apple dev website 

      Go to: <https://developer.apple.com/account/resources/certificates/list>
      Then `Create new profile` and select `developer ID application`

   3. Save certificate CN as github repo secret: `MACOS_CERT_COMMON_NAME`

- [x] Add generated certificate + key to Github repo secret

   1. Generate a p12 file including the certificate and private key
      
      > It will ask for a password, generate a strong one and save somewhere safe.

   2. Encode the p12 file in base64.

   3. Add the password and base64 encoded p12 file in 2 github repo secrets: `MACOS_CERT` and `MACOS_CERT_PASSWD`.

- [x] Generate notarization credentials

   <https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/#gathering-the-notarization-information>

   1. Generate a new app-specific passwords, save it as a secret named `MACOS_NOTARIZATION_PASSWD`.

   2. Get your team ID and save the value under a github repo secret `MACOS_NOTARIZATION_TEAM_ID`.

   3. Save your apple id as secret `MACOS_NOTARIZATION_APPLE_ID`

- [x] Add a step during `package-client` for the macos app packaging sign

   <https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/#defining-the-code-signing-step>

   1. Add dedicated step to setup keychain:
       
      ```yaml
      - name: Codesign app bundle
        # Extract the secrets we defined earlier as environment variables
        if: matrix.platform == 'macos'
        env: 
          MACOS_CERT: ${{ secrets.MACOS_CERT }}
          MACOS_CERT_PASSWD: ${{ secrets.MACOS_CERT_PASSWD }}
          MACOS_CERT_COMMON_NAME: ${{ secrets.MACOS_CERT_COMMON_NAME }}
          MACOS_CI_KEYCHAIN_PASSWD: ${{ secrets.MACOS_CI_KEYCHAIN_PASSWD }}
        run: |
          # Turn our base64-encoded certificate back to a regular .p12 file
          
          echo $MACOS_CERT | base64 --decode > certificate.p12

          # We need to create a new keychain, otherwise using the certificate will prompt
          # with a UI dialog asking for the certificate password, which we can't
          # use in a headless CI environment
          
          security create-keychain -p "$MACOS_CI_KEYCHAIN_PASSWD" build.keychain 
          security default-keychain -s build.keychain
          security unlock-keychain -p "$MACOS_CI_KEYCHAIN_PASSWD" build.keychain
          security import certificate.p12 -k build.keychain -P "$MACOS_CERT_PASSWD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$MACOS_CI_KEYCHAIN_PASSWD" build.keychain
      ```

   2. Configure env variable for `electron-builder-notarize`

      <https://www.npmjs.com/package/electron-builder-notarize?activeTab=readme>

<https://federicoterzi.com/blog/automatic-code-signing-and-notarization-for-macos-apps-using-github-actions/>
