### ISSUE TITLE
Update Parsec SaaS emails

### ISSUE THREAD

**Issue by fabienSvtr** [Scille/parsec-cloud#8260]
- [x] Scille/parsec-bms#1056
  - [x] create an app with a sender to manage all email templates in the project
  - [x] update global base template (header & footer) according to mock-ups
  - [x] improve template format (html & css)
  - [x] update feedback email template according to mock-ups to work with the whole new email sending system
  - [x] add a send_email CLI command taking recipients, template name and email locale as params
  - [x] use django i18n (.po files) to translate email templates
  - [x] update documentation to reflect all the changes (env vars, new commands, new format...)
- [x] Update email templates according to mock-ups:  https://www.figma.com/design/jDUDnJmNiEwwy7UsAUI9cd/Email?m=auto&t=RzNzhIPVpBn34wUL-6
  - [x] Invitation mail https://github.com/Scille/parsec-cloud/pull/8289
  - [x] Scille/parsec-bms/issues/1095
  - [x] Scille/parsec-bms#1057
  - [x] Scille/parsec-bms#1058
  - [x] Scille/parsec-bms#1059
  - [x] Scille/parsec-bms#1060
  - [x] Scille/parsec-bms#1061
- [ ] Scille/parsec-bms#1062

**Comment by NicoTuxx** [comment]
Don't forget to update base_mail template in /bms:
- [ ] uncomment footer part
- [ ] add links, images...

**Comment by NicoTuxx** [comment]
Update parsec sign subscription mail content: guide the user on what to do now (download parsec if not done, launch it (link maybe)...)
