### ISSUE TITLE
Make libparsec logging destination configurable

### ISSUE THREAD

**Issue by vxgmichel** [Scille/parsec-cloud#8518]
At the moment, the logs issued by the libparsec (such as `log::warn!(...)`) do not appear in electron log file (`logs/main.log`).

On windows, they are printed to the console, although they typically don't appear when the app is started with `npm run electron:open`. The log level can be configured using `RUST_LOG=warn` for instance, but the destination cannot.

This makes debugging in the test environment quite cumbersome. Also, we do want to log the libparsec warning to a file so that we can retrieve it from the clients that encountered issues, for investigating purposes.

For those reasons, we want to have a way to configure the libparsec logging system and have proper defaults for both debugging environnements and client environnements. Note that the libparsec logging should also be configurable from the CLI.

@FirelightFlagboy what's the current state of libparsec logging on linux again?

## TODOs

- [ ] Write libparsec logs to a file on Windows
- [ ] Add env variable to customize log file location
- [ ] Increase the log level to warn

**Comment by FirelightFlagboy** [comment]
> @FirelightFlagboy what's the current state of libparsec logging on linux again?

On **unix** system, electron prevent libparsec to write anything to stdout/stderr, so for logging we write the logs to a temp file:

https://github.com/Scille/parsec-cloud/blob/61af65ed2419e2caca6ee62fdaf18b2c63a47992/bindings/electron/src/lib.rs#L35-L51

We use a temp file to not have to handle log rotation & co 

Note that this behavior is only prevent for the electron client, for the CLI we don't have do to that since we can log directly to the console.
