### ISSUE TITLE
[🚀 | Feature request]: Display user freeze state & filter  

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8694]
When a user is frozen, this information is not displayed in the Users page.

The goal of this issue is **not** to change frozen status in the GUI. Currently, this is only available at server-level via API, we are not sure if we should open this to organization admins. 

Instead, the idea is to only display the frozen status in the Users page, probably in the status column:
![image](https://github.com/user-attachments/assets/b9708f21-8cb7-4262-8b7c-dc29a5b5b482).

Note that the status is not displayed in the Grid view (is it wanted?)   
![image](https://github.com/user-attachments/assets/e4ee7173-a0d6-4d1d-a769-6d896d9f0691)

## To keep in mind

- Frozen status should be added as filter
- Priority of the displayed status: Revoked > Frozen > Active
- Explain what each status means (tooltip)

## Task List

- [x] #8695
- [x] #8696
- [x] #8697

### Setup

TODO: Describe how to local setup for testing this feature (testbed ? local server ? ...)

### Tests

TODO: List some test cases to be performed when reviewing the feature.

**Comment by AureliaDolo** [comment]
On the backend side:

- [ ] expose get_user_info protocol in authenticated cmds (there is already a method retrieving that info from the db/memory, and server's userinfo alreadu has the frozen field)
- [ ] (add a protocol cmd to get_user_info)
- [ ] add frozen field to libparsec's UserInfo
- [ ] in client_list_user 
	1. retrieve userinfo from certifops
	2. update it with current frozen status through a authenticated cmds
- [ ] update binding's generator's ClientInfo with frozen status
- [ ] generate bindings
- [ ] add tests	


Open questions: 
- Should the frozen info be somewhere in the certifops ?
	- No, there is no associated certificate, but we won't know which users are frozen without a specific request
	- Yes, it is data about a user. But when should it be updated ?
- Is there already a protocol command that could be adapted to this usage ?

**Comment by AureliaDolo** [comment]
Possible implementations:
1. update current client_list_user
	a. add a get_freeze_info(vec userId) -> vec UserInfo authenticated cmds
	b. add a get_frozen_users() -> Vec UserId
	- use a or b it in client list_user after retrieving user info from local certificates to update the user info certifops provided 
2. Add a get_remote_users_info(vec UserId) -> vec (userID, bool) binding
	- the client side implementation would only propagate the query to the server and do nothing else
	- in the GUI it would be used after list users to complete data with server's data. 
	

The advantage of option 2 is that all the locally available data is displayed as soon as possible without having to wait for the server. 

The advantage of using 1 is to show only up to date data. If this takes more than 5s per call to listUsers, another option must be preferred.

Note that currently function user_get_user_info in the server retrieve user info for one User, so whatever solution we choose, it would be better to have a batched version of that method to limit DB access (it is not implemented in memory ?)

What about a cache ?
- Where ?
	- in the certifops, because that's where the data about users is stored. It does not make sense to put it in the certifops because there is no freeze certificate
	- in a dedicated component ?
- Keeping it up to date
	- on freeze the server sends an event
	- only when freeze data is demanded (that would make sense mostly in option 2, so local data could include the last known freeze status)

**Comment by NicoTuxx** [comment]
We want a unique command to get the set of frozen users

**Comment by AureliaDolo** [comment]
Only admin users will be able to see frozen status, as this requires a server request.
