### ISSUE TITLE
[🚀 | Feature request]: File viewer for common files

### ISSUE THREAD

**Issue by mmmarcos** [Scille/parsec-cloud#8854]
See #8514 for details

For this issue, the files concerned are the most common file types:
- Images that can natively be displayed in a browser (png, jpeg, gif, webp, svg, ...)
- Video that can natively be played in a browser (mp4, webm, ...)
- Audio that can natively be played in a browser (mp3, wav, ...)
- Text and code formats (XML, txt, cpp, ...)
- Xlsx as it is the most common spreadsheet file
- Docx as it is the most common editable document file.
- Pdf as it is the most common document file

TODO:
- [x] Mock-ups for viewers
- [X] Read the content of a file when trying to open it. Tested in #8837
- [X] Detect a file type to be able to use the right component. Done in 8853 using https://www.npmjs.com/package/file-type. 
- [X] Dispatch to the right component for each file. Tested in #8837
- [x] Mock the files in web mode to ease debugging/dev
- [x] Feature to open the file outside Parsec with the default app
- [x] Setting to bypass viewers in desktop mode
- [x] Develop technical components & features: #9011
- [x] #9052
- [x] #9053
- [x] #9054
- [x] #9055
- [x] #9057
- [x] #9058
- [x] #9059
- [x] #9061
- [x] #9060
